/**
 * Thai UI copy (LOC-01: the platform launches in Thai). Centralised so every
 * user-facing surface renders Thai under <html lang="th">.
 */
export const th = {
  brand: "ProBooking",
  home: {
    tagline: "ตรวจสอบแล้ว • พร้อมทำงาน • จองได้ • คุ้มครองการชำระเงิน",
    description:
      "ตลาดสองด้านสำหรับเวรคลินิกชั่วคราว คลินิกค้นหา เปรียบเทียบ เชิญ และจองบุคลากรที่ผ่านการตรวจสอบ ส่วนบุคลากรควบคุมเวลาว่าง ยอมรับเงื่อนไขที่ชัดเจน และรับเงินที่ตรวจสอบได้",
    phase: "เฟส 0 — การตรวจสอบแบบคอนเซียร์จ กรุงเทพฯ และปริมณฑล",
    flowLink: "→ ทดลองขั้นตอนการจอง (เดโมสำหรับนักพัฒนา)",
    opsLink: "→ แดชบอร์ดฝ่ายปฏิบัติการ",
    financeLink: "→ การกระทบยอดฝ่ายการเงิน",
  },
  common: {
    refresh: "รีเฟรช",
    none: "ไม่มี",
    error: "ข้อผิดพลาด",
    loading: "กำลังโหลด…",
  },
  a11y: {
    skipToContent: "ข้ามไปยังเนื้อหาหลัก",
    dismiss: "ปิด",
    notifications: "การแจ้งเตือน",
  },
  badge: {
    clinic: "คลินิก",
    professional: "บุคลากร",
    credential_hold: "ระงับเอกสาร",
  },
  nav: {
    home: "หน้าแรก",
    ops: "ปฏิบัติการ",
    finance: "การเงิน",
    flow: "เดโม",
    openMenu: "เปิดเมนู",
    closeMenu: "ปิดเมนู",
  },
  ops: {
    title: "แดชบอร์ดฝ่ายปฏิบัติการ",
    metricShifts: "เวร (เปิดรับ)",
    metricBookings: "การจอง",
    metricCompleted: "เสร็จสิ้น",
    metricHeld: "ระงับไว้",
    metricCases: "เคสที่เปิด",
    metricExceptions: "รายการกระทบยอดผิดปกติ",
    pending: "รอการตรวจสอบ",
    verify: "ตรวจสอบ",
    openCases: "เคสที่เปิดอยู่",
    resolveHold: "ปลดการระงับ",
  },
  finance: {
    title: "การเงิน — การกระทบยอด",
    exportCsv: "ส่งออก CSV (REP-02)",
    paymentOrders: "คำสั่งชำระเงิน",
    captured: "เก็บเงินแล้ว",
    payouts: "จ่ายออก",
    refunds: "คืนเงิน",
    exceptions: "รายการผิดปกติ",
    colBooking: "การจอง",
    colUndistributed: "ยังไม่กระจาย",
    colConserved: "สมดุล",
    showing: (shown: number, total: number) => `แสดง ${shown} จาก ${total} รายการ`,
    conservedYes: "สมดุล",
    conservedNo: "รายการผิดปกติ",
    exportStarted: "กำลังดาวน์โหลด finance-export.csv",
  },
  flow: {
    title: "ProBooking — ขั้นตอนการจอง",
    description:
      "ลงทะเบียนและตรวจสอบคลินิกกับบุคลากร สร้างข้อเสนอที่ผูกพัน ยอมรับ (soft hold) ยืนยันการจอง เสร็จสิ้นและจ่ายเงินให้บุคลากร แล้วให้รีวิว",
    run: "รันขั้นตอนการจอง",
    bookingId: "รหัสการจอง",
    bookingConfirmed: "ยืนยันการจองแล้ว",
    compensation: "ค่าตอบแทน",
    serviceFee: "ค่าบริการ (12%)",
    tax: "ภาษี",
    total: "รวม",
    completePayout: "เสร็จสิ้นและจ่ายเงิน",
    paidOut: "จ่ายเงินแล้ว",
    payoutToProfessional: (state: string) => `ให้บุคลากร (การจอง ${state})`,
    leaveReviews: "ให้รีวิว (ทั้งสองฝ่าย)",
    reviewsPublished: "เผยแพร่รีวิวแล้ว",
    ratingShown: (avg: string, count: number) => `คะแนนบุคลากร: ${avg} (${count} รีวิว)`,
    ratingHidden: "คะแนนบุคลากร: ยังไม่แสดง (ต้องมี 3 รีวิว)",
    steps: {
      registered: "ลงทะเบียนแล้ว",
      verified: "ตรวจสอบโดยปฏิบัติการ",
      shiftPosted: "โพสต์เวรแล้ว",
      applied: "บุคลากรสมัครแล้ว",
      offerCreated: "สร้างข้อเสนอแล้ว",
      accepted: "บุคลากรยอมรับแล้ว",
      confirmed: "ยืนยันการจองแล้ว",
    },
    stepDetail: {
      registered: (state: string) => `คลินิก + บุคลากร (สถานะ ${state})`,
      verified: "คลินิก + บุคลากร → ตรวจสอบแล้ว",
      shiftPosted: (state: string) => `เวรเปิดรับ (${state})`,
      applied: "ส่งใบสมัครแล้ว (ไม่ผูกพัน)",
      offerCreated: (state: string, fee: string) => `สถานะ=${state}, ค่าบริการ=${fee}`,
      accepted: (state: string) => `สถานะ=${state} (soft hold, ยังไม่ใช่การจอง)`,
      confirmed: (state: string) => `สถานะ=${state}`,
    },
  },
} as const;
