/**
 * Thai UI copy (LOC-01: the platform launches in Thai). Centralised so the staff- and
 * user-facing surfaces render Thai under <html lang="th">. Numbers/brand stay as-is; the
 * /flow page is a developer/e2e demo harness and is intentionally left in English.
 */
export const th = {
  brand: "ProBooking",
  home: {
    tagline: "หาเวรคลินิกได้บุคลากรที่ตรวจสอบแล้ว จ่ายเงินอย่างปลอดภัย",
    lead: "คลินิกจองบุคลากรที่ตรวจสอบแล้ว — เงินถูกคุ้มครองจนกว่าเวรจะเสร็จ",
    description:
      "ตลาดสองด้านสำหรับเวรคลินิกชั่วคราว คลินิกค้นหา เชิญ และจองบุคลากรที่ผ่านการตรวจสอบ ส่วนบุคลากรควบคุมเวลาว่าง ยอมรับเงื่อนไขที่ชัดเจน และรับเงินที่ตรวจสอบได้",
    region: "กรุงเทพฯ และปริมณฑล · แพทย์และทันตแพทย์",
    phase: "เฟส 0 — คอนเซียร์จ กรุงเทพฯ และปริมณฑล",
    metadataDescription:
      "ตลาดสองด้านสำหรับเวรคลินิกชั่วคราวในประเทศไทย จองบุคลากรที่ตรวจสอบแล้ว พร้อมการชำระเงินที่คุ้มครอง",
    ctaPrimary: "เริ่มเดโม",
    ctaSecondary: "ดูวิธีทำงาน",
    trust: ["ตรวจสอบแล้ว", "พร้อมทำงาน", "จองได้", "คุ้มครองการชำระเงิน"],
    howTitle: "ทำงานอย่างไร",
    howSubtitle: "จากประกาศเวรถึงจ่ายเงิน สี่ขั้นตอนที่ตรวจสอบได้",
    howClinicTitle: "มุมคลินิก",
    howProTitle: "มุมบุคลากร",
    stepsClinic: [
      { t: "ประกาศเวร", d: "ลงเวรที่เปิดรับ พร้อมเงื่อนไขและค่าตอบแทนที่ชัดเจน" },
      { t: "ส่งข้อเสนอ", d: "ดูผู้สมัครแล้วส่งข้อเสนอผูกพันหนึ่งฉบับ" },
      { t: "ชำระและคุ้มครองเงิน", d: "ยอมรับข้อเสนอแล้วกันเงินไว้ก่อนยืนยันการจอง" },
      { t: "รับงานและรีวิว", d: "ยืนยันเมื่องานเสร็จ ระบบจ่ายเงินให้บุคลากร" },
    ],
    stepsPro: [
      { t: "หาเวร", d: "ดูเวรที่เปิดรับจากคลินิกที่ตรวจสอบแล้ว" },
      { t: "สมัครหรือรับข้อเสนอ", d: "การสมัครยังไม่ผูกพัน — รอข้อเสนอจากคลินิก" },
      { t: "ยอมรับและรอชำระ", d: "ยอมรับเงื่อนไขแล้วรอคลินิกชำระเงิน" },
      { t: "ทำงานและรับเงิน", d: "มาถึง ส่งงานเสร็จ ติดตามการจ่ายเงิน แล้วรีวิว" },
    ],
    steps: [
      { t: "ประกาศเวร", d: "คลินิกที่ตรวจสอบแล้วลงเวรที่เปิดรับ พร้อมเงื่อนไขและค่าตอบแทนที่ชัดเจน" },
      { t: "เชิญและเสนอ", d: "บุคลากรสมัครหรือถูกเชิญ คลินิกส่งข้อเสนอผูกพันหนึ่งฉบับ" },
      { t: "ยืนยันและคุ้มครองเงิน", d: "ยอมรับข้อเสนอแล้วกันเงินไว้ก่อนยืนยันการจอง" },
      { t: "ทำงานและรับเงิน", d: "เมื่อเสร็จงาน ระบบจ่ายเงินให้บุคลากรพร้อมบันทึกที่ตรวจสอบได้" },
    ],
    pickTitle: "เลือกบทบาทเพื่อเริ่มเดโม",
    pickSubtitle: "เข้าสู่ระบบด้วยบัญชีทดลองของแต่ละบทบาท แล้วขับเคลื่อนทั้งขั้นตอนด้วยตนเอง — คลิกเดียว รหัส OTP กรอกให้อัตโนมัติ",
    pickPath: "แนะนำ: เริ่มที่คลินิก → สลับไปบุคลากร → ปฏิบัติการ → การเงิน",
    pickParty: "คู่สัญญา",
    pickStaff: "ทีมภายใน",
    flowSmokeNote: "สำหรับทีมพัฒนา: ทดสอบทั้งขั้นตอนอัตโนมัติ",
    surfacesTitle: "เข้าใช้งาน",
    surfacesSubtitle: "เลือกพื้นผิวที่ต้องการ — เดโมจอง ปฏิบัติการ หรือการเงิน",
    flowLink: "ทดสอบระบบ",
    flowDesc: "เดโมสำหรับนักพัฒนา — เดินครบทั้งขั้นตอนตั้งแต่จองถึงจ่ายเงิน",
    opsLink: "แดชบอร์ดฝ่ายปฏิบัติการ",
    opsDesc: "ตรวจสอบคลินิกและบุคลากร จัดการเคสและการระงับ",
    financeLink: "การกระทบยอดฝ่ายการเงิน",
    financeDesc: "กระทบยอดคำสั่งชำระเงินและตรวจสอบการอนุรักษ์ยอด",
    open: "เปิด",
  },
  signin: {
    title: "เข้าใช้งานในบทบาทต่าง ๆ",
    subtitle: "เลือกบัญชีทดลองเพื่อเข้าใช้งานในมุมมองของแต่ละบทบาท",
    demoNote: "บัญชีทดลองสำหรับเดโมเท่านั้น — รหัส OTP จะกรอกให้อัตโนมัติ",
    reset: "รีเซ็ตข้อมูลเดโม",
    resetting: "กำลังรีเซ็ต…",
    resetHelp: "ล้างข้อมูลเดโมกลับชุดตั้งต้น — การจองและการยืนยันที่ทำไว้จะหาย",
    resetDone: "รีเซ็ตข้อมูลเดโมแล้ว",
    backHome: "หรือเริ่มจากหน้าแรก",
  },
  clinic: {
    gate: "เข้าสู่ระบบเป็นเจ้าของคลินิกเพื่อจัดการเวร",
    gateCta: "เลือกบัญชีเข้าสู่ระบบ",
    subtitle: "ประกาศเวร ส่งข้อเสนอหนึ่งฉบับ ยืนยันและคุ้มครองเงิน",
    owner: "เจ้าของคลินิก",
    postTitle: "ประกาศเวรใหม่",
    compLabel: "ค่าตอบแทน (บาท)",
    urgent: "ด่วน",
    categoryLabel: "ประเภทเวร",
    startLabel: "เริ่มเวร",
    post: "ประกาศเวร",
    posted: "ประกาศเวรแล้ว",
    shiftsTitle: "เวรของฉัน",
    actionTitle: "ต้องดำเนินการ",
    bookingsTitle: "การจอง",
    sendOffer: "ส่งข้อเสนอ",
    offerSent: "ส่งข้อเสนอแล้ว",
    confirmPay: "ยืนยัน & จ่าย",
    confirmTitle: "ยืนยันการจองและชำระเงิน",
    confirmNote: "หลังชำระ ระบบจะยืนยันการจองและคุ้มครองการชำระเงิน",
    confirmed: "ยืนยันและกันเงินแล้ว",
    acceptCompletion: "รับงาน & จ่ายเงิน",
    acceptedCompletion: "รับงานและจ่ายเงินแล้ว",
    cancel: "ยกเลิก",
    cancelled: "ยกเลิกแล้ว",
    cancelTitle: "ยกเลิกการจอง",
    cancelBody: "การจองที่ยืนยันแล้วอาจมีค่าธรรมเนียมหรือการคืนเงินตามเงื่อนไข",
    review: "รีวิวบุคลากร",
    reviewed: "รีวิวแล้ว",
    emptyShifts: "ยังไม่มีเวร — ประกาศเวรด้านบนเพื่อเริ่มหาบุคลากร",
    emptyCandidates: "ยังไม่มีผู้สมัคร — รอบุคลากรสมัครหรือเชิญ",
    emptyBookings: "เมื่อบุคลากรยอมรับและคุณจ่ายเงิน การจองจะปรากฏที่นี่",
    signOut: "ออกจากระบบ",
    comp: "ค่าตอบแทน",
    fee: "ค่าบริการ 12%",
    total: "รวม",
    checkout: "สรุปยอดชำระ",
  },
  pro: {
    gate: "เข้าสู่ระบบเป็นบุคลากรเพื่อหาเวรและรับงาน",
    gateCta: "เลือกบัญชีเข้าสู่ระบบ",
    subtitle: "หาเวร ยอมรับข้อเสนอ ทำงาน และรับเงิน",
    role: "บุคลากร",
    offersTitle: "ข้อเสนอถึงฉัน",
    openTitle: "เวรที่เปิดรับ",
    jobsTitle: "งานของฉัน",
    apply: "สมัคร",
    applied: "สมัครแล้ว",
    applyNote: "การสมัครยังไม่ผูกพัน — คลินิกต้องส่งข้อเสนอก่อน",
    accept: "ยอมรับ",
    accepted: "ยอมรับข้อเสนอแล้ว (รอคลินิกยืนยัน)",
    decline: "ปฏิเสธ",
    declined: "ปฏิเสธข้อเสนอแล้ว",
    offerTitle: "ข้อเสนอจากคลินิก",
    offerNote: "ยังไม่ใช่การจอง จนกว่าคลินิกจะชำระเงิน",
    arrive: "มาถึงแล้ว",
    arrived: "บันทึกการมาถึงแล้ว",
    complete: "ส่งงานเสร็จ",
    completed: "ส่งงานเสร็จแล้ว",
    completeGate: "บันทึกการมาถึงก่อนส่งงานเสร็จ",
    review: "รีวิวคลินิก",
    reviewed: "รีวิวแล้ว",
    reviewScore: "คะแนน",
    reviewComment: "ความคิดเห็น (ไม่บังคับ)",
    emptyOffers: "ยังไม่มีข้อเสนอ — สมัครเวรด้านล่างก่อน",
    emptyShifts: "ยังไม่มีเวรเปิดรับ",
    emptyJobs: "ยังไม่มีงานที่ยืนยันแล้ว",
    availabilityNote: "ในเฟสนี้เวลาว่างตั้งโดยทีมเดโม — บุคลากรที่ตรวจสอบแล้วจะปรากฏในรายชื่อผู้สมัคร",
    verified: "ตรวจสอบแล้ว",
    signOut: "ออกจากระบบ",
  },
  flow: {
    title: "ทดสอบระบบ (สำหรับทีมพัฒนา)",
    subtitle:
      "หน้านี้ไม่ใช่เดโมลูกค้า — ใช้ทดสอบขั้นตอนจองครบวงจรอัตโนมัติเท่านั้น สำหรับเดโมจริงให้เริ่มจากหน้าแรก",
    banner: "หน้านี้สำหรับทีมพัฒนา — ไม่ใช่เดโมลูกค้า",
    bannerLink: "ไปที่ตัวเลือกบทบาทบนหน้าแรก",
    run: "เริ่มขั้นตอนการจอง",
    running: "กำลังเดินขั้นตอน…",
    phaseBooking: "การจอง",
    phaseSettlement: "ปิดยอดและรีวิว",
    progress: (done: number, total: number) => `ขั้นตอน ${done} จาก ${total}`,
  },
  common: {
    refresh: "รีเฟรช",
    none: "ไม่มี",
    emptyTable: "ยังไม่มีรายการ",
    loading: "กำลังโหลด…",
    close: "ปิด",
    confirm: "ยืนยัน",
    cancel: "ยกเลิก",
    verified: "ตรวจสอบแล้ว",
    paymentProtected: "คุ้มครองการชำระเงิน",
  },
  nav: {
    home: "หน้าแรก",
    clinic: "คลินิกของฉัน",
    pro: "งานของฉัน",
    ops: "ปฏิบัติการ",
    finance: "การเงิน",
    flow: "ทดสอบระบบ",
    signin: "เข้าใช้งาน",
    switchRole: "สลับบทบาท",
    signOut: "ออกจากระบบ",
  },
  status: {
    offer: {
      PendingResponse: "รอบุคลากรตอบ",
      AwaitingPayment: "รอชำระเงิน",
      Converted: "เปลี่ยนเป็นการจองแล้ว",
      Declined: "ปฏิเสธแล้ว",
      Withdrawn: "ถอนแล้ว",
      Expired: "หมดอายุ",
      PaymentFailed: "ชำระไม่สำเร็จ",
    },
    booking: {
      Confirmed: "ยืนยันแล้ว · คุ้มครองการชำระเงิน",
      InProgress: "กำลังปฏิบัติงาน",
      AwaitingCompletion: "รอรับรองว่าเสร็จ",
      ServiceCompleted: "เสร็จสิ้น",
      Cancelled: "ยกเลิกแล้ว",
      Archived: "เก็บถาวร",
    },
    payout: {
      NotEligible: "ยังไม่พร้อมจ่าย",
      Processing: "กำลังจ่าย",
      Paid: "จ่ายเงินแล้ว",
      Failed: "จ่ายไม่สำเร็จ",
      Held: "ระงับการจ่าย",
      Reversed: "ย้อนกลับแล้ว",
    },
    verification: {
      Draft: "ร่าง",
      Submitted: "ส่งแล้ว",
      UnderReview: "กำลังตรวจสอบ",
      NeedsInformation: "ขอข้อมูลเพิ่ม",
      Verified: "ตรวจสอบแล้ว",
      Rejected: "ไม่ผ่าน",
      Suspended: "ระงับ",
      Expired: "หมดอายุ",
      Closed: "ปิดแล้ว",
    },
    case: {
      Open: "เปิด",
      AwaitingUser: "รอผู้ใช้",
      UnderReview: "กำลังตรวจสอบ",
      InProgress: "กำลังดำเนินการ",
      Resolved: "ปิดแล้ว",
      Reopened: "เปิดใหม่",
    },
    shift: {
      Published: "เปิดรับ",
      booked: "จองแล้ว",
      hasOffer: "มีข้อเสนอแล้ว",
      hasApplicants: (n: number) => `มีผู้สมัคร ${n} คน`,
    },
    application: {
      Submitted: "สมัครแล้ว",
      Shortlisted: "คัดเลือกแล้ว",
      OfferSent: "ส่งข้อเสนอแล้ว",
    },
  },
  categories: {
    general: "ทั่วไป",
    physician: "แพทย์",
    dentist: "ทันตแพทย์",
  },
  professions: {
    physician: "แพทย์",
    dentist: "ทันตแพทย์",
  },
  ops: {
    title: "คิวปฏิบัติการ",
    subtitle: "ตรวจสอบ · เคส · การระงับ",
    emptyPending: "คิวว่าง — ไม่มีรายการรอตรวจสอบ",
    emptyCases: "ไม่มีเคสที่เปิดอยู่ตอนนี้",
    emptyMetrics: "ยังไม่มีกิจกรรม — รีเซ็ตเดโมหรือเริ่มการจองใหม่",
    metricShifts: "เวร (เปิดรับ)",
    metricBookings: "การจอง",
    metricCompleted: "เสร็จสิ้น",
    metricHeld: "ระงับไว้",
    metricCases: "เคสที่เปิด",
    metricExceptions: "รายการกระทบยอดผิดปกติ",
    pending: "รอการตรวจสอบ",
    openSuffix: "เปิดรับ",
    kind: { clinic: "คลินิก", professional: "บุคลากร", insurance: "ประกันภัย" } as Record<string, string>,
    caseKind: {
      credential_hold: "ระงับคุณสมบัติ",
      completion_review: "ตรวจหลังเสร็จงาน",
      cancellation_support: "สนับสนุนการยกเลิก",
    } as Record<string, string>,
    verify: "ผ่าน",
    needsInfo: "ขอข้อมูลเพิ่ม",
    reject: "ไม่ผ่าน",
    verifiedClinic: "คลินิกผ่านการตรวจสอบแล้ว",
    verifiedPro: "บุคลากรผ่านการตรวจสอบแล้ว",
    needsInfoDone: "ขอข้อมูลเพิ่มแล้ว",
    rejected: "ปฏิเสธการตรวจสอบแล้ว",
    openCases: "เคสที่เปิดอยู่",
    resolveHold: "ปลดการระงับ",
    activeBookings: "การจองที่กำลังดำเนินอยู่",
    emptyActive: "ไม่มีการจองที่กำลังดำเนินอยู่",
    holdCredential: "ระงับการจอง",
    suspend: "ระงับใบอนุญาต",
    heldBadge: "ระงับไว้",
    suspendedBadge: "ระงับแล้ว",
    insuranceVerified: "ตรวจสอบประกันภัยแล้ว",
    credentialSuspended: "ระงับใบอนุญาตแล้ว",
    credentialHeld: "ระงับการจองแล้ว",
    reasonLabel: "เหตุผล (ไม่บังคับ)",
    reasonPlaceholder: "เช่น ใบอนุญาตหมดอายุ",
    auditTitle: "บันทึกการตรวจสอบ",
    auditEmpty: "ยังไม่มีบันทึก",
  },
  finance: {
    title: "การเงิน — การกระทบยอด",
    subtitle: "กระทบยอดคำสั่งชำระเงินกับเงินที่เก็บแล้ว และตรวจการอนุรักษ์ยอด",
    summaryLine: (captured: string, payouts: string, exceptions: number) =>
      `เก็บเงินแล้ว ${captured} · จ่ายออก ${payouts} · ผิดปกติ ${exceptions} รายการ`,
    conservationHelp:
      "ยอดตรงเมื่อเงินที่เก็บ = จ่ายออก + คืนเงิน + ค่าบริการ (ไม่มีเงินหายหรือเกิน)",
    exportCsv: "ส่งออก CSV",
    reconciliation: "รายการกระทบยอด",
    paymentOrders: "คำสั่งชำระเงิน",
    captured: "เก็บเงินแล้ว",
    payouts: "จ่ายออก",
    refunds: "คืนเงิน",
    exceptions: "รายการผิดปกติ",
    colBooking: "การจอง",
    colUndistributed: "ยังไม่กระจาย",
    colConserved: "ตรงยอด",
    conservedYes: "ตรงยอด",
    conservedNo: "ไม่ตรงยอด",
    showing: (shown: number, total: number) => `แสดง ${shown} จาก ${total} รายการ`,
    refund: "คืนเงิน",
    refundTitle: "คืนเงิน (ต้องมีผู้อนุมัติคนที่สอง)",
    refundAmount: "จำนวนเงิน (บาท)",
    refundReason: "เหตุผล",
    refundReasonPlaceholder: "เช่น คืนเงินตามดุลยพินิจ",
    refundMax: (amount: string) => `คืนได้สูงสุด ${amount}`,
    propose: "เสนอคืนเงิน",
    cancel: "ยกเลิก",
    pendingApprovals: "รออนุมัติคืนเงิน",
    approve: "อนุมัติ & คืนเงิน",
    emptyApprovals: "ไม่มีรายการรออนุมัติ",
    emptyRecon: "ยังไม่มีคำสั่งชำระเงิน — ให้คลินิกยืนยันการจองในเดโมก่อน",
    proposedBy: "เสนอโดย",
    refundProposed: "บันทึกคำขอคืนเงินแล้ว รอผู้อนุมัติคนที่สอง",
    refundApproved: "อนุมัติและคืนเงินแล้ว",
    exportStarted: "กำลังดาวน์โหลด finance-export.csv",
  },
  staffLogin: {
    title: {
      operations: "เข้าสู่ระบบฝ่ายปฏิบัติการ",
      finance: "เข้าสู่ระบบฝ่ายการเงิน",
    },
    description:
      "เข้าสู่ระบบด้วยหมายเลขโทรศัพท์ของเจ้าหน้าที่ที่ได้รับอนุญาต ระบบจะส่งรหัส OTP ทาง SMS",
    phoneLabel: "หมายเลขโทรศัพท์ของเจ้าหน้าที่",
    sendCode: "ส่งรหัส OTP",
    codeLabel: "รหัส OTP",
    signIn: "เข้าสู่ระบบ",
    requestNewCode: "กลับไปขอรหัสใหม่",
    sendCodeError: "ส่งรหัส OTP ไม่สำเร็จ กรุณาลองอีกครั้ง",
    signInError: "เข้าสู่ระบบไม่สำเร็จ กรุณาตรวจสอบรหัส OTP แล้วลองอีกครั้ง",
    signOut: "ออกจากระบบ",
    demoHint: "เดโม: ใช้บัญชีทดลองด้านล่าง (รหัส OTP กรอกให้อัตโนมัติ)",
    useDemo: "เข้าสู่ระบบด้วยบัญชีทดลอง",
  },
  a11y: {
    primaryNav: "เมนูหลัก",
    openMenu: "เปิดเมนู",
    closeMenu: "ปิดเมนู",
    notifications: "การแจ้งเตือน",
    dismissNotification: "ปิดการแจ้งเตือน",
    switchToLight: "เปลี่ยนเป็นโหมดสว่าง",
    switchToDark: "เปลี่ยนเป็นโหมดมืด",
    lightMode: "โหมดสว่าง",
    darkMode: "โหมดมืด",
    skipToContent: "ข้ามไปยังเนื้อหา",
    reconciliationTable: "ตารางกระทบยอดคำสั่งชำระเงิน",
  },
  notFound: {
    title: "ไม่พบหน้านี้",
    description: "ลิงก์นี้อาจหมดอายุ หรือหน้าที่ต้องการย้ายไปแล้ว",
    home: "กลับหน้าแรก",
  },
  errors: {
    generic: "เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง",
    connection: "เชื่อมต่อระบบไม่สำเร็จ กรุณาลองอีกครั้ง",
    noPermission: "บัญชีนี้ไม่มีสิทธิ์เข้าถึงหน้านี้",
    sessionExpired: "เซสชันหมดอายุ กรุณารีเฟรชหน้าแล้วเข้าสู่ระบบอีกครั้ง",
    tooManyRequests: "ส่งคำขอถี่เกินไป กรุณารอสักครู่แล้วลองอีกครั้ง",
    phoneRequired: "กรุณากรอกหมายเลขโทรศัพท์",
    invalidOtp: "รหัส OTP ไม่ถูกต้องหรือหมดอายุแล้ว กรุณาลองอีกครั้งหรือขอรหัสใหม่",
  },
} as const;

/**
 * Map a raw API/network error to friendly Thai copy (from PR #9). Pairs with `errorFrom`
 * in lib/api, which already extracts the server's message; this turns that (or a network
 * failure) into a sentence the user reads, falling back to the caller's default.
 */
export function getThaiErrorMessage(error: unknown, fallback: string = th.errors.generic): string {
  const message = error instanceof Error ? error.message.toLowerCase() : "";
  if (
    message.includes("too many requests") ||
    message.includes("too many otp") ||
    message.includes("retry later") ||
    message.startsWith("429:")
  ) {
    return th.errors.tooManyRequests;
  }
  if (message.includes("invalid or expired code")) return th.errors.invalidOtp;
  if (message.includes("phone required")) return th.errors.phoneRequired;
  if (message.includes("requires role") || message.includes("not a member") || message.includes("forbidden") || message.startsWith("403:")) {
    return th.errors.noPermission;
  }
  if (message.includes("authentication required") || message.startsWith("401:")) {
    return th.errors.sessionExpired;
  }
  if (
    message.includes("failed to fetch") ||
    message.includes("fetch failed") ||
    message.includes("network") ||
    message.includes("timeout") ||
    message.includes("abort")
  ) {
    return th.errors.connection;
  }
  return fallback;
}
